# Generated by Django 2.2.3 on 2020-11-03 12:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon_entities', '0006_auto_20201103_1224'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pokemonentity',
            name='pokemon',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                                    related_name='entities', to='pokemon_entities.Pokemon'),
        ),
    ]
