# Generated by Django 2.2.3 on 2020-11-13 10:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon_entities', '0011_auto_20201110_1633'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pokemon',
            name='previous_evolution',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT,
                                    related_name='next_evolutions', to='pokemon_entities.Pokemon',
                                    verbose_name='Предыдущая эволюция'),
        ),
    ]
